new_http_archive (
        name = "gsl",
        url = "https://github.com/Microsoft/GSL/archive/64a7dae4c6fb218a23b3d48db0eec56a3c4d5234.zip",
        strip_prefix = "GSL-64a7dae4c6fb218a23b3d48db0eec56a3c4d5234",
        sha256 = "7fa59a76b0a7f8f27af60af7b64bec6cd26b69a6f8fd2e678954b8626fe20840",
        build_file_content = """
cc_library(
  name = "gsl",
  hdrs = glob([ "include/gsl/*" ]),
  includes = ["include"],
  visibility = ["//visibility:public"],
)
        """,
        )

# TODO gaz
# Change to this when I get version of bazel that allows symlinks within zip files that 
# don't leak outside of their own directory structure
# https://github.com/bazelbuild/bazel/commit/79ebb32e77f134e2f6496dd532bf9574d4198676

# new_http_archive (
#         name = "spdlog",
#         url = "https://github.com/gabime/spdlog/archive/5ab033fba5710fc9fc7fbff901e27a8d9d92778e.zip",
#         strip_prefix = "spdlog-5ab033fba5710fc9fc7fbff901e27a8d9d92778e",
#         sha256 = "9349dfe3a81d4ff3c732f3d1e7d64a003545be39030eb8e92ddee7ea57ad2c8e",
#         build_file_content = """
# cc_library(
#         name = "spdlog",
#         hdrs     = glob([
#             "include/spdlog/**/*.h",
#             "include/spdlog/**/*.cc",
#             ]),
#         includes = ["include"],
#         visibility = ["//visibility:public"],
#         )
#         """,
#         )

# Hold spdlog locally for now
new_local_repository (
        name = "spdlog",
        path = "third_party/spdlog-5ab033fba5710fc9fc7fbff901e27a8d9d92778e",
        build_file_content = """
cc_library(
        name = "spdlog",
        hdrs = glob([ "include/spdlog/**/*.h", "include/spdlog/**/*.cc", ]),
        includes = ["include"],
        visibility = ["//visibility:public"])
        """,
        )

# 94b7a8da66d833a6b83de9ed27ce21492c15d8ca
        # url = "https://github.com/nhloman/json/94b7a8da66d833a6b83de9ed27ce21492c15d8ca.zip"

new_http_archive (
        name = "json",
        # url = "https://github.com/Microsoft/GSL/archive/64a7dae4c6fb218a23b3d48db0eec56a3c4d5234.zip",
        url = "https://github.com/nlohmann/json/archive/94b7a8da66d833a6b83de9ed27ce21492c15d8ca.zip",
        strip_prefix = "json-94b7a8da66d833a6b83de9ed27ce21492c15d8ca",
        sha256 = "cd0f83b159bfacc9874bbe6e3d7a22366b0ed52aabf48f6a1ebfb398484e4c19",
        build_file_content = """
cc_library(
  name = "json",
  hdrs = glob([ "single_include/*" ]),
  includes = ["single_include"],
  visibility = ["//visibility:public"],
)
        """,
        )

new_http_archive (
        name = "cxxopts",
        url = "https://github.com/jarro2783/cxxopts/archive/e792760ab91b30028f49df4edd72687d4f0e684c.zip",
        strip_prefix = "cxxopts-e792760ab91b30028f49df4edd72687d4f0e684c",
        sha256 = "469c641e686b5dd7b0faf1c7ef76d6aa9f53ecbcde439bd3c5743aceef4469ef",
        build_file_content = """
cc_library(
  name = "cxxopts",
  hdrs = glob([ "include/*" ]),
  includes = ["include"],
  visibility = ["//visibility:public"],
)
        """,
        )

