new_http_archive (
        name = "gsl",
        url = "https://github.com/Microsoft/GSL/archive/64a7dae4c6fb218a23b3d48db0eec56a3c4d5234.zip",
        strip_prefix = "GSL-64a7dae4c6fb218a23b3d48db0eec56a3c4d5234",
        sha256 = "7fa59a76b0a7f8f27af60af7b64bec6cd26b69a6f8fd2e678954b8626fe20840",
        build_file_content = """
cc_library(
  name = "gsl",
  hdrs = glob([ "include/gsl/*" ]),
  includes = ["include"],
  visibility = ["//visibility:public"],
)
        """,
        )

# TODO gaz
# Change to this when I get version of bazel that allows symlinks within zip files that 
# don't leak outside of their own directory structure
# https://github.com/bazelbuild/bazel/commit/79ebb32e77f134e2f6496dd532bf9574d4198676

# new_http_archive (
#         name = "spdlog",
#         url = "https://github.com/gabime/spdlog/archive/5ab033fba5710fc9fc7fbff901e27a8d9d92778e.zip",
#         strip_prefix = "spdlog-5ab033fba5710fc9fc7fbff901e27a8d9d92778e",
#         sha256 = "9349dfe3a81d4ff3c732f3d1e7d64a003545be39030eb8e92ddee7ea57ad2c8e",
#         build_file_content = """
# cc_library(
#         name = "spdlog",
#         hdrs     = glob([
#             "include/spdlog/**/*.h",
#             "include/spdlog/**/*.cc",
#             ]),
#         includes = ["include"],
#         visibility = ["//visibility:public"],
#         )
#         """,
#         )

# Hold spdlog locally for now
new_local_repository (
        name = "spdlog",
        path = "third_party/spdlog-5ab033fba5710fc9fc7fbff901e27a8d9d92778e",
        build_file_content = """
cc_library(
        name = "spdlog",
        hdrs = glob([ "include/spdlog/**/*.h", "include/spdlog/**/*.cc", ]),
        includes = ["include"],
        visibility = ["//visibility:public"])
        """,
        )


